Make Support for rails 7.1 explicit since 7.2 is there as well
puzzle/wagons pull request #52
Opened 2024-10-23 06:59 UTC by kronn

2024-10-24 06:49 UTC, codez commented
Thanks for the PR. While adding the 7.1 Gemfile makes sense, Gemfile.lock should also be updated to 7.2. Otherwise, 7.1 is tested twice, which adds no additional benefits. 

Could you also look into that test failure?

2025-01-24 09:48 UTC, codez requested changes

2025-01-24 09:48 UTC, codez commented on .github/workflows/build.yml
> +          # Exclude Ruby 3.0 since it isn't supported with rails 7.2
Da sollte wohl 3.1 stehen?

2025-01-24 09:48 UTC, codez commented on wagons.gemspec
> +  s.add_dependency 'concurrent-ruby', '< 1.3.5'
Warum braucht es diese Dependency neuerdings? Die wird nirgends direkt verwendet? Oder warum muss die Version limitiert werden?

2025-01-24 09:48 UTC, codez commented on Gemfile.lock
> +    rails (7.2.0)
Inzwischen ist 7.2.2.1 draussen. Ich würde das sicher bis dahin updaten. Idealerweise gleich bis 8.0, dann mit einem neuen rails72.gemfile.

2025-01-24 09:48 UTC, codez commented on .github/workflows/build.yml
> +        ruby-version: ["3.1", "3.2"]
Wenn wir gleich dabei sind, allenfalls 3.3 und ev 3.4 aufnehmen?

2025-01-28 10:02 UTC, Vakmeth commented on wagons.gemspec
> +  s.add_dependency 'concurrent-ruby', '< 1.3.5'
Brauchen wir nicht mehr, wäre nötig gewesen wenn wir die Tests weiterhin auch mit rails 6.1 oder 7.0 laufen gelassen hätten.

2025-01-28 10:54 UTC, codez approved these changes
:+1: Sieht gut aus, werde das so mergen und releasen

2025-01-28 10:56 UTC, merged